### ISSUE TITLE
Error when running circlator: can't find canu version

### ISSUE THREAD

**Issue by AnnaSyme** [sanger-pathogens/circlator#111]
I am using the new version of canu (version 1.6). 

On running circlator (version 1.5.1), I get:

circlator.external_progs.Error: Found canu but couldn't get version.
Cannot continue

Thanks.

**Comment by ssjunnebo** [comment]
Hi Anna,

This has been fixed now, but it might take a while until the changes become available with pip.

**Comment by AnnaSyme** [comment]
Thank you!

**Comment by mindsgoat** [comment]
I am still having the same issue with Circlator v1.5.5 and Canu v2.1.1, both installed with conda

**Comment by BGemler** [comment]
I am running into the same issue as above. Circlator v1.5.5, Canu v2.2. Error message "circlator.external_progs.Error: Found canu but couldn't get version."

Should I roll back to an earlier Canu version? Please advise @ssjunnebo

**Comment by xyssty1e** [comment]
The same Error. This method may work.
Find the script "external_progs.py" and change "Caun" to "canu" in line 22.
